### ISSUE TITLE
Add verbose logging as an option

### ISSUE THREAD

**Issue by TheFitzZZ** [swellaby/vsts-mirror-git-repository#48]
## Description
Add an optioon to toggle verbose logging output.

## Value
Would allow to observe current progress. Currently, especially if it is a long running task, long waits can either mean a lot of data is being moved, the system is slow, or there is a underlying problem. Verbose logging would allow quick insight.

**Comment by calebcartwright** [comment]
Thanks @TheFitzZZ (and for your review and kind words!)

What did you have in mind around logging? I'm sure git has some kind of `-v` or `--verbose` option that we could support, although I'm not sure what extra output that would add on the `clone` and `push` steps we take. 

There's also the pipeline level settings for debug and diagnostics that make the entire pipeline output **much** more verbose

https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops#build-and-release-logs

**Comment by TheFitzZZ** [comment]
You are correct - for some reason I also thought I had seen a more verbose output of git, but that must have been a bad dream. Sorry for the trouble :-)

**Comment by calebcartwright** [comment]
No worries!
