### ISSUE TITLE
PAT is pass in url rather than in Authorization header : not working on Azure Devops Server

### ISSUE THREAD

**Issue by mgodlewski** [swellaby/vsts-mirror-git-repository#84]
## Environment Details
* **Pipeline**
  * [*] Build
* **Agent OS**
  * [*] Windows

* **Mirror Task Configuration**
  * **Mirror Git Repo Task version**: 1.1.12
  * **Mirror Source Repo System**
    * [*] Azure DevOps Server (formerly TFS) v Dev18.M170.6
  

## Description
The clone is not working since the PAT is added in the repo url (https://myPAT@server/repository.git) and not as a Authorization header (-c http.extraHeader="Authorization: Basic $B64Pat"), like described in the documentation : https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat

## Log Output
```
Starting: Mirror Git Repository to Gitlab OAB
==============================================================================
Task         : Mirror Git Repository
Description  : A straightforward utility to mirror one Git repository to another location
Version      : 1.1.12
Author       : Swellaby
Help         : [More Information](https://github.com/swellaby/vsts-mirror-git-repository)
==============================================================================
/usr/local/bin/git -c http.sslVerify=true clone --mirror https://myPAT@server/repository.git
Clonage dans le dépôt nu 'repository.git'
fatal: could not read Password for 'https://myPAT@server/repository.git': terminal prompts disabled
##[error]Error: The process '/usr/local/bin/git' failed with exit code 128
Finishing: Mirror Git Repository to another repo
```

**Comment by calebcartwright** [comment]
Thanks for reaching out @mgodlewski, what version of AzDo Server are you using, 2019?

**Comment by mgodlewski** [comment]
The version of AzDo Server is "Dev18.M170.6"

**Comment by calebcartwright** [comment]
Thanks, best we can tell, Microsoft silently dropped support for auth in the userinfo subcomponent on the URI in newer versions of Server which is most likely what you're running into there.

Going to close this in favor of #86 and #85
